### ISSUE TITLE
Přidat setup.py

### ISSUE THREAD

**Issue by stinovlas** [setnicka/ulozto_downloader#1]
Ahoj, co takhle přidat `setup.py`, aby si mohli lidé nainstalovat balík přes `pip` a neřešit ručně závislosti apod.? Šel by pak i umístit na http://pypi.org/, ale jestli to nechceš, tak jde stále přes `pip` instalovat i z url (např. na githubu).

**Comment by stinovlas** [comment]
Btw. pokud bude zájem, tak ten `setup.py` klidně napíšu.

**Comment by CZechBoY** [comment]
nebo aspoň přidat `requirements.txt`
