### ISSUE TITLE
Uloz.to zřemě vrátilo staré rozhraní

### ISSUE THREAD

**Issue by stinovlas** [setnicka/ulozto_downloader#10]
Vypadá to, že `?do=slowDirectDownload` přestalo fungovat. Naopak zase funguje starý způsob stahování se zadáváním captcha kódu. Takže poslední změny s odstraněním captchy revertneme?

**Comment by stinovlas** [comment]
Nebo alespoň u některých souborů.

Např. https://uloz.to/!NMZZk0SxF7gg/michal-tucny-prodavac-mp3 mi funguje bez captchy (a ne s ní).

A naopak https://uloz.to/!ugNo5UnrsNUJ/comeback-s01e04-pomahat-a-chranit-avi mi jde jen s captchou (a ne bez ní).

**Comment by stinovlas** [comment]
V nápovědě se píše:

```
Kdy se u pomalého stažení zobrazuje ověřovací kód captcha?

Opsání captcha kódu slouží jako bezpečnostní prvek k ověření uživatele.
U nově nahraných souborů a malých souborů do 50 MB není nutné tento kód opisovat.
Fajnšmekři, kteří si rádi užívají luštění hlavolamů stále captchu na některých souborech najdou.
```

**Comment by setnicka** [comment]
Nejlepší by asi bylo první zkusit verzi bez captchy a teprve pokud nevyjde, tak zobrazit uživateli captchu. Pokud se k tomu nikdo nedostane dřív, tak to zkusím do pár dnů spáchat a otestovat.

**Comment by 11p5G** [comment]
Je známo, že každé stažení souboru se u nich zapisuje do logů. Je tam minimálně vidět, jestli byl stažen podle pravidel.
Pokud tedy určité množství uživatelů začne používat neoficiální nástroj na stahování, je jisté, že to zaznamenají a  budou to jistě řešit.
Úpravy mechanizmu ulož.to se někdy provádějí i 3x týdně (hlavně kvůli malwaru).

Nové pravidla captchy se aplikují na nově nahrané soubory od nějakého data. U starších souborů to zůstává při starém.

**Comment by stinovlas** [comment]
> Nové pravidla captchy se aplikují na nově nahrané soubory od nějakého data. U starších souborů to zůstává při starém.

Minimálně několik dní bylo možné stahovat bez zadání captcha kódu jakékoliv soubory, mj. i takové, které už teď nejdou.

**Comment by 11p5G** [comment]
> Minimálně několik dní bylo možné stahovat bez zadání captcha kódu jakékoliv soubory, mj. i takové, které už teď nejdou.

Bylo to na jeden den, kdy mělo ulož.to "narozeniny".

**Comment by stinovlas** [comment]
Ne, nebylo. Fungovalo to skoro týden. Čemu není rozumět na "minimálně několik dní"?

**Comment by 11p5G** [comment]
Protože soubory, které jsem nahrál v ten den, jsou bez captchy do teď.

**Comment by stinovlas** [comment]
Nechápu co se tu snažíš sdělit. Ano, uloz.to občas mění své rozhraní. To všichni víme. Tvrzení, že bez captchy šly jakékoliv soubory stáhnout jen v jeden den je nepravdivé, šlo to téměř týden (nemám přesné logy, ale z data uložení souborů můžu udělat aspoň nějaký dolní a horní odhad, pokud bych musel). Nadále jsou zřejmě některé soubory dostupné v původním módu před změnou (protože jdou stáhnout starým rozhraním) a některé v novém bezcaptchovém módu (protože jdou stáhnout novým rozhraním). To všechno už tady padlo. Takže co chceš říct?
