### ISSUE TITLE
Název binárního programu

### ISSUE THREAD

**Issue by exander77** [setnicka/ulozto_downloader#13]
Nebylo by dobré tomu dát nějaký rozumný název?

Aby se například binárka jmenovala (download):
`dulozto`

Pro svůj projekt vyhledávače bych zvolil například (search, find):
`sulozto` (moc se mi nelíbí to su na začátku)
`fulozto`

**Comment by JanPokorny** [comment]
`sulozto` zní jako slovenský příkaz k souložení

**Comment by exander77** [comment]
@JanPokorny To mě upřímně nenapadlo.

**Comment by setnicka** [comment]
V novém pip balíčku se spustitelný soubor jmenuje `ulozto-downloader`, na což by <tab>-completion měl napovědět docela jednoduše (právě kvůli <tab>-completion mi přijde důležité aby název spustitelného skriptu měl prefix `ulozto`).

**Comment by JanPokorny** [comment]
Myslím že teď bys jen pro konzistenci měl přejmenovat repo 😄 (Vlastně proč ne, URLs by měla zůstat všechna fungovat...)

**Comment by setnicka** [comment]
ACK, přejmenování repa vlastně dává smysl.
