### ISSUE TITLE
AUR balíček

### ISSUE THREAD

**Issue by petrbel** [setnicka/ulozto_downloader#18]
@setnicka neplánuješ udělat balíček do AURu? Učitě by to ocenila spousta lidí :)

**Comment by JanPokorny** [comment]
Spíš balíček pro pip, ne? To vezme jednou ranou všechny OS kde Python běží, a ocení to větší spousta lidí než oba čeští uživatelé ArchLinuxu...

**Comment by petrbel** [comment]
@JanPokorny haha to je fakt :)

**Comment by setnicka** [comment]
Jo, balíček pro pip je dobrý nápad. Nějaký dřívější pokus už existoval, ale teď jsem to udělal pořádněji (společně s nějakým refaktoringem kódu). Takže račte použít :)
```shell
$ pip3 install ulozto-downloader
$ ulozto-downloader -h
```
Samostatný AUR balíček asi vytvářet spíše nebudu, takže zavírám tuhle issue s tím, že existuje tohle.

**Comment by petrbel** [comment]
Super! To určitě přijde vhod :) 

@setnicka Btw tohle by Tě mohlo zajímat pro ještě více automatizace: https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
