### ISSUE TITLE
Provoz na serveru bez X

### ISSUE THREAD

**Issue by masscream** [setnicka/ulozto_downloader#19]
Zdravím, snažím se tento script rozběhnout na jednom serveru, který nemá DE ani X server, pouze konzolové prostředí. Nevím nakolik to nazvat chybou nebo spíš zkrátka vlastností scriptu, že nebyl pro tato prostředí napsán, nicméně nešlo by ošetřit čtení captchy jiným způsobem? (např v ASCII artu / ručním zadáváním). Děkuji za úvahu.

Starting downloading for url 'https://uloz.to/file/qBqmjuDxQqju/policejni-akademie-1-93m-1984-usa-czdabing-hd-1080p-i-avi'
Getting info (filename, filesize, ...)
CAPTCHA protected download - CAPTCHA challenges will be displayed
CAPTCHA image challenge...
Traceback (most recent call last):
  File "ulozto_downloader.py", line 423, in <module>
    download(args.url, args.parts, args.output)
  File "ulozto_downloader.py", line 318, in download
    download_url = get_captcha_download_link(url)
  File "ulozto_downloader.py", line 109, in get_captcha_download_link
    captcha_answer = get_captcha_user_input("http:" + captcha_data['new_captcha_data']['image'])
  File "ulozto_downloader.py", line 182, in get_captcha_user_input
    root = tk.Tk()
  File "/usr/lib64/python3.6/tkinter/__init__.py", line 2023, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

**Comment by setnicka** [comment]
No nevím jakým rozumným způsobem zobrazit CAPTCHU v ASCII artu.
Ale asi by mělo jít napsat tomu webksicht, že by se to ovládalo vzdáleně přes HTTP, nebo by to minimálně v tomhle případě vystavilo přes HTTP ten CAPTCHA obrázek s textovým políčkem na jeho zadání. Patche vítány :)

**Comment by masscream** [comment]
Kdysi dávno jsem pro uloz.to používal toto, nevím jestli to ještě funguje po tolika změnách API, ale tehdy to fungovalo a zobrazovalo to captchu právě v ASCII (byl někdy porod to přečíst, ale princip byl fajn).
https://github.com/mcrapet/plowshare-modules-legacy/blob/master/uloz_to.sh

**Comment by masscream** [comment]
Update: našel jsem aspoň provizorní workaround dle tohoto návodu
https://askubuntu.com/questions/203173/run-application-on-local-machine-and-show-gui-on-remote-display
díky němuž se dají GUI okna posílat na stranu X klienta... i tak by nebylo špatné se časem obejít bez X úplně, když už je program psaný v tui. Ale i tak dělá výbornou práci.

**Comment by setnicka** [comment]
Díky integraci #32 už se dá s přepínačem `--auto-captcha` využívat louskání pomocí TensorFlowLite, které docela funguje. Tuto issue tedy zavírám.

Pro případné jiné louskání na serveru by teď mělo jít docela lehce předat downloaderu i jiný CAPTCHA breaker (přes dependency injection), pull requesty v tomto směru do budoucna určitě vítány.

**Comment by muniv11111** [comment]
já i s auto-captcha končím na tomhle:

 import _tkinter # If this fails your Python may not be configured for Tk
ModuleNotFoundError: No module named '_tkinter'

já bohužel v srpnu zkoušel ale tk jsem nerozjel.. nemám tam root na to serveru, a prostě jsem kompiloval furt něco ale pořád sem se v tom motal už nevím.. viz třeba zde https://stackoverflow.com/questions/5459444/tkinter-python-may-not-be-configured-for-tk nebo zde https://askubuntu.com/questions/1224230/how-to-install-tkinter-for-python-3-8

**Comment by setnicka** [comment]
Můžu zkusit dát import tkinter podmíněný jenom při použití ručního opisování.

**Comment by muniv11111** [comment]
> Můžu zkusit dát import tkinter podmíněný jenom při použití ručního opisování.

a z čeho bych to opisoval, dkyž tam není žadný display?
nebo myslíš jako že bych používal teda tu moji verzi web app na louskání? já to měl v té mé verzi bez tkinter a samo mi to bralo řešení captchy z toho webu.. jen sem prostě zavislý na tom webu a jak to vypne on ví koho myslím... :-)

**Comment by setnicka** [comment]
Ten poslední comment asi nechápu.

Každopádně na PyPI je teď verze 1.6.1 která importuje tkinter jenom tehdy, když je potřeba. Takže `pip3 install --upgrade ulozto-downloader`. U mě na serveru to funguje :)

**Comment by muniv11111** [comment]
python3 ./ulozto-downloader --auto-captcha --parts 4 https://uloz.to/file/pUgUgmeXOc7W/ledove-kralovstvi-2-cz-dabing-mp4
Downloading model from https://github.com/JanPalasek/ulozto-captcha-breaker/rele                             ases/download/v2.2/model.tflite
100.0% 14147584 / 14140796
Downloading of the model finished
Starting downloading for url 'https://uloz.to/file/pUgUgmeXOc7W/ledove-kralovstvi-2-cz-dabing-mp4'
Getting info (filename, filesize, ...)
CAPTCHA protected download - CAPTCHA challenges will be displayed

Traceback (most recent call last):lenge...
  File "./ulozto-downloader", line 48, in <module>
    main()
  File "./ulozto-downloader", line 44, in main
    d.download(args.url, args.parts, args.output)
  File "/home24/muniv/opt/python-3.8.1/lib/python3.8/site-packages/ulozto_downloader/downloader.py", line 156, in download
    download_url = page.get_captcha_download_link(
  File "/home24/muniv/opt/python-3.8.1/lib/python3.8/site-packages/ulozto_downloader/page.py", line 127, in get_captcha_download_link
    captcha_answer = captcha_solve_func(captcha_image, print_func=print_func)
  File "/home24/muniv/opt/python-3.8.1/lib/python3.8/site-packages/ulozto_downloader/captcha.py", line 86, in __call__
    import tflite_runtime.interpreter as tflite
  File "/home24/muniv/opt/python-3.8.1/lib/python3.8/site-packages/tflite_runtime/interpreter.py", line 36, in <module>
    from tflite_runtime import _pywrap_tensorflow_interpreter_wrapper as _interpreter_wrapper
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /home24/muniv/opt/python-3.8.1/lib/python3.8/site-package                            s/tflite_runtime/_pywrap_tensorflow_interpreter_wrapper.cpython-38-x86_64-linux-gnu.so)

zatím neřeš.. :-) možná to jako lama vidím složitě.. hází to tohle..

**Comment by JanPalasek** [comment]
Zkus na serveru updatovat balíčky:

apt-get update
apt-get install libstdc++6

https://github.com/lhelontra/tensorflow-on-arm/issues/13

**Comment by muniv11111** [comment]
no to je to že nemám root jedná se o placený seedhost kde jsem bez rootu, marně jsem to zkoušel už v létě s tím nejak pohnout ale neptal jsem se chytrých hlav tady.. :-)

cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

uname --m
x86_64

uname -p
x86_64


 apt-get update
Reading package lists... Done
W: chmod 0700 of directory /var/lib/apt/lists/partial failed - SetupAPTPartialDirectory (1: Operation not permitted)
E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
E: Unable to lock directory /var/lib/apt/lists/
W: Problem unlinking the file /var/cache/apt/pkgcache.bin - RemoveCaches (13: Permission denied)
W: Problem unlinking the file /var/cache/apt/srcpkgcache.bin - RemoveCaches (13: Permission denied)

**Comment by muniv11111** [comment]
tak mi to správce updatoval a ted mám tohle zase... 🤔

  import tflite_runtime.interpreter as tflite
  File "/home24/muniv/opt/python-3.8.1/lib/python3.8/site-packages/tflite_runtime/interpreter.py", line 36, in <module>
    from tflite_runtime import _pywrap_tensorflow_interpreter_wrapper as _interpreter_wrapper
ImportError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /home24/muniv/opt/python-3.8.1/lib/python3.8/site-packages/tflite_runtime/_pywrap_tensorflow_interpreter_wrapper.cpython-38-x86_64-linux-gnu.so)

**Comment by muniv11111** [comment]
tak jsem to nějak rozjel.. ale byla to fuška..

protože sám kompilovat nejak tensorflow opravdu bych nedal.. tak jsem hledal..a jediné co jsem našel na 16.04, OR s glibc 2.23
bylo tohle: []( https://github.com/evdcush/TensorFlow-wheels/releases/download/tf-1.12.0-py37-cpu-ivybridge/tensorflow-1.12.0-cp37-cp37m-linux_x86_64.whl)

sice to hází nějak deprecated hlášky nějak 1type assynonym of type in future version in numpy, ale auto-captcha s tím jede..

všechny vyšší verze tensorflow vyžadovali Glibc 2.27

pak jsem ještě musel upravit dva řádky v captcha.py:

    -   import tflite_runtime.interpreter as tflite
    +  import tensorflow as tf

   -   interpreter = tflite.Interpreter(model_content=self.model_content)
   +  interpreter = tf.contrib.lite.Interpreter(model_content=self.model_content)

**Comment by JanPalasek** [comment]
@muniv11111 To jsi nainstaloval celý tensorflow, ten je pěkně velký. Možná stačilo nějakou starou verzi tflite. No, hlavně, že to jede.

**Comment by muniv11111** [comment]
> @muniv11111 To jsi nainstaloval celý tensorflow, ten je pěkně velký. Možná stačilo nějakou starou verzi tflite. No, hlavně, že to jede.

já vím, ale tak místa na tom seedhostu mám dost.. právě že jsem hledal jak blázen žadné tflite 1.12 s glibc 2.23 na linux není možné najít.. a vyšší verze 1.13 už chtějí 2.27 jestli jsem něco nepřehledl ..

ještě tam mám nějak problémys pornfile.. stahují se jen dvě vlákna nějak tak zase skáče multiprocessing chyby.. přitom z uloz.to to nepozuruju.. ten pornfile musí @setnick nutne doladit.. nemá tam podle mne ani podmíněné když je to příme stahováni bez captchy, pak se to nerozjede.. mrknu přesne ješte co to hází a hodím to do issue o pornfile.. :-)
