### ISSUE TITLE
Nahradit mutiprocessing za asyncio

### ISSUE THREAD

**Issue by stinovlas** [setnicka/ulozto_downloader#2]
Uvažoval jsi o náhradě `multiprocessing` za `asyncio`? U aplikace, která je takhle moc závislá na I/O operacích by `asyncio` asi vycházelo na zdroje líp (především u mnoha stahovacích vláken najednou), nemluvě o jednodušším kódu.

**Comment by setnicka** [comment]
V rámci refaktoringu jsem zkoušel, jak by současný kód vyšel s `asyncio`. A možná jsem to vzal za špatný konec, ale i když jsem to zkusil několika různými způsoby, tak mi přišlo, že to `asyncio` oproti `multiprocessing` komplikuje. Takže zatím projekt zůstává u použití `multiprocessing` a tohle zatím zavírám jako wont fix.

Případnému pull requestu někdy v budoucnosti se nebráním, ale neměl by setím kód moc zkomplikovat.
