### ISSUE TITLE
Skript přestal fungovat

### ISSUE THREAD

**Issue by jise** [setnicka/ulozto_downloader#20]
Ahoj, asi dva dny zpět nejspíš došlo k nějaké změně na uloz.to, která to způsobila. Nefunguje ani vžum. Testováno na windows a linuxu.

**Comment by setnicka** [comment]
V průběhu víkendu se na to podívám a fixnu, pokud to půjde.

**Comment by JanPokorny** [comment]
@setnicka Klasika, opět zamíchali to co vrací který endpoint a jaká jsou na ně URL. V logice se nic zásadně nezměnilo.

**Comment by w0k3** [comment]
Páni, podarilo sa to niekomu fixnúť?

**Comment by JanPokorny** [comment]
@w0k3 Já http://vzum.8u.cz/ fixnul, nicméně Linux podpora je momentálně buggy kvůli unrelated UI chybě. Můžeš zkusit jestli ti to pojede, na některých instalacích to padá při zobrazení captcha okna.

**Comment by w0k3** [comment]
@JanPokorny no práve mne ani Vžum nejde (na Linuxe), kusne sa pri "Vlákno 0 žádá Ulož.to o soubor, pokus 1".

**Comment by setnicka** [comment]
Nestihl jsem se na to zatím podívat, ale až dořeším aktuální pomoc pro MO s uspořádáním ústředního kola olympiády online, tak se k tomu snad brzo dostanu :innocent: 
![obrazek](https://i.giphy.com/media/f9MexdeCXXmH85PE8l/giphy.webp)

**Comment by JanPokorny** [comment]
@w0k3 Stáhni nejnovější verzi (teď jsem pushoval), pusť z terminálu přes "mono Vzum.exe" a napiš mi co ti to vyblije v terminálu před tím, než (pokud vůbec) se to sekne. => JmenujuSePopcorn@USA.com

**Comment by w0k3** [comment]
@JanPokorny posledná verzia funguje. Nie je to úplne stabilné, raz sa mi napríklad miesto captcha zobrazilo prázdne čierne okno a nešlo zavrieť, ani nič zadať, len zabiť aplikáciu - v konzole nebolo nič. Odvtedy sa mi to nestalo a jeden súbor sa úspešne stiahol, takže jazdí to. :+1:
