### ISSUE TITLE
Output file created in current dir, not in --output <dir>

### ISSUE THREAD

**Issue by kkoouu** [setnicka/ulozto_downloader#22]
Dnes jsem poprve vyzkousel, vse super, jen takova drobnost - jednotlive casti jsou vytvareny korektne dle  parametru --output ( kontroloval jsem behem stahovani), finalni soubor se ale objevi v aktualnim adresari.

Priklad:
$ ./ulozto_downloader.py --output /links/tmp/ https://uloz.to/file/vIluYcpO4uDD/dira-el-hoyo-2019-cz-titulky-mkv

File: Díra (El hoyo,2019)Cz.Titulky.mkv
URL: https://uloz.to/file/vIluYcpO4uDD/dira-el-hoyo-2019-cz-titulky-mkv
Size: 5173.91MB
Download type: CAPTCHA protected
Parts: 10 x 517.39MB

[Part 1]	Successfully downloaded 517.39MB in 0:49:06
[Part 2]	Successfully downloaded 517.39MB in 0:49:05
[Part 3]	Successfully downloaded 517.39MB in 0:49:10
[Part 4]	Successfully downloaded 517.39MB in 0:49:08
[Part 5]	Successfully downloaded 517.39MB in 0:49:06
[Part 6]	Successfully downloaded 517.39MB in 0:49:04
[Part 7]	Successfully downloaded 517.39MB in 0:49:06
[Part 8]	Successfully downloaded 517.39MB in 0:49:05
[Part 9]	Successfully downloaded 517.39MB in 0:49:06
[Part 10]	Successfully downloaded 517.39MB in 0:49:07

All downloads finished, merging files...
All files merged, output file is 'Díra (El hoyo,2019)Cz.Titulky.mkv'

$ ls -la /links/tmp/Díra\ \(El\ hoyo\,2019\)Cz.Titulky.mkv 
ls: cannot access '/links/tmp/Díra (El hoyo,2019)Cz.Titulky.mkv': No such file or directory

$ ls Díra\ \(El\ hoyo\,2019\)Cz.Titulky.mkv 
'Díra (El hoyo,2019)Cz.Titulky.mkv'

**Comment by setnicka** [comment]
Fixed by #24
