### ISSUE TITLE
Kontrola / v nazvu souboru

### ISSUE THREAD

**Issue by zdar** [setnicka/ulozto_downloader#26]
Program nekontroluje pritomnost lomitka v nazvu souboru na Uloz.to . Stazeni casti souboru pak havaruje protoze se snazi ukladat do neexistujiciho adresare (cast nazvu je povazovana za adresar)

**Comment by masscream** [comment]
Potvrzuji, pokud jde o tento problém...

`File: Vynález zkázy / L'invention Diabolique / Aventures fantastiques / The Fabulous World of Jules Verne / The Deadly Invention 1958, CZ - EN tit.mkv
URL: https://uloz.to/file/xRKccMAGKyjE/
Size: 1374.42MB
Download type: CAPTCHA protected
Parts: 21 x 65.45MB

[Part 1]	Starting downloadProcess Process-1:
Traceback (most recent call last):lenge...
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()	Waiting for CAPTCHA...
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "./ulozto_downloader.py", line 237, in download_part
    with open(part['filename'], 'ab') as f:
FileNotFoundError: [Errno 2] No such file or directory: "./Vynález zkázy / L'invention Diabolique / Aventures fantastiques / The Fabulous World of Jules Verne / The Deadly Invention 1958, CZ - EN tit.mkv.part01of21"
[Part 11]	Waiting for CAPTCHA...
[Part 12]	Waiting for CAPTCHA...
[Part 13]	Waiting for CAPTCHA...
[Part 14]	Waiting for CAPTCHA...
[Part 15]	Waiting for CAPTCHA...
[Part 16]	Waiting for CAPTCHA...
[Part 17]	Waiting for CAPTCHA...
[Part 18]	Waiting for CAPTCHA...
[Part 19]	Waiting for CAPTCHA...
[Part 20]	Waiting for CAPTCHA...
[Part 21]	Waiting for CAPTCHA...
`

**Comment by setnicka** [comment]
Mělo by být fixed by #25
