### ISSUE TITLE
ReCaptcha je vždy neplatná

### ISSUE THREAD

**Issue by jansramek** [setnicka/ulozto_downloader#30]
Ahoj, v posledních dnech pravděpodobně přestala fungovat práce s recaptchou, resp. všechny zadané recaptchy jsou vyhodnoceny jako chybné.

**Comment by fboranek** [comment]
To protoze se zmenila odpoved. Ocekavane je

```json
{"downloadLink": "..."}
```

a dostane

```json
{"slowDownloadLink": "..."}
```

po zamene ve skriptu to funguje.

**Comment by jansramek** [comment]
Myslím, že problém bude i v google recaptche (v2), která se v tuto chvíli objevuje před zahájením stahování.

**Comment by fboranek** [comment]
Muze byt. Prvni captcha prosla hned, ale dalsi captchi k dalsim castem stahovani jsem musel vyplnovat po 1 minute, jinak jsem stejne dostal "Nevalidni odpoved". Trafik jsem nezkoumal.

**Comment by daanoo410** [comment]
Bude to niekedy opravené? Ani vžum nefunguje

**Comment by MatusCicko** [comment]
> Prvni captcha prosla hned, ale dalsi captchi k dalsim castem stahovani jsem musel vyplnovat po 1 minute, jinak jsem stejne dostal "Nevalidni odpoved".

U mna prisla "nevalidna odpoved" cca po kazdej druhej alebo tretej casti. Skusal som to obist tym, ze by kazda cast pouzivala separatny `requests.Session` s nahodne vybranym `User-Agent` http headerom. To nepomohlo, asi tu ide o nejaky IP rate limiting :man_shrugging: 

Pockat 1 minutu (nie menej) funguje aj mne, tak som to pridal do kodu. Toto riesenie je daleko od idealneho, ale snad je to lepsie ako nic. Pridavam to ako PR k https://github.com/DuchGhast/ulozto_downloader/tree/patch-1, ktory riesi zmenu `downloadLink` -> `slowDownloadLink`. Mozeme to plz mergnut, @DuchGhast?

**Comment by MatusCicko** [comment]
Ahoj @setnicka, bolo by prosim mozne checknut a mergnut https://github.com/setnicka/ulozto_downloader/pull/31/? Opravuje to tento reportovany problem (mam to lokalne otestovane).

**Comment by JanPokorny** [comment]
Potvrzuji že #31 funguje. Co se týče mého průzkumu, tak Ulož.to zavedlo limit, kolik unikátních sessions z jedné IP může během minuty začít stahovat soubor (2). Session má už dávno limit 1 aktivní stahování (což kontroluje přímo download server), tedy nevidím možnost, jak to obejít. Pro Vžum jsem použil stejnou strategii (čekat 1 minutu při překročení).

**Comment by JanPokorny** [comment]
Možné alternativní řešení by bylo dříve než za minutu vyřešit prezentovanou ReCaptcha2... https://github.com/mikeyy/nonoCAPTCHA

**Comment by JanPalasek** [comment]
Také potvrzuji, že #31 funguje. Bude to někdy zamergováno, vyřešeno jinak, nebo tento projekt umřel?

**Comment by setnicka** [comment]
Pardon, neměl jsem teď moc čas a tohle jsem trochu zazdil. Díky @JanPokorny za pošťouchnutí mimo GitHub, právě koukám na pull request.

**Comment by setnicka** [comment]
Fixed in #31
