### ISSUE TITLE
Nahrazení tabulátorů mezerami

### ISSUE THREAD

**Issue by stinovlas** [setnicka/ulozto_downloader#9]
Dávám ke zvážení nahradit tabulátory čtyřmi mezerami.

[PEP8](https://www.python.org/dev/peps/pep-0008/#indentation) mluví celkem jasně:

1) Use 4 spaces per indentation level.

2) Spaces are the preferred indentation method. Tabs should be used solely to remain consistent with code that is already indented with tabs.

Osobně tabulátory v Pythoním kódu nepředpokládám a hodně mě matou. Přiznávám, že i nedávné editace jsem dělal tak, že jsem si na začátku nahradil tabulátory za mezery a na konci je zase konvertoval zpátky. U takhle malého projektu mi jednorázové přepnutí nepřijde jako problém. Klidně k tomu udělám i pull request, pokud bude Jirka souhlasit.

**Comment by exander77** [comment]
Tohle podporuji.

**Comment by setnicka** [comment]
Osobně považuji používání mezer pro indentaci v Pythonu jako jednu z největších chyb v PEP8. Proč nepoužívat pro indentaci klávesu a znak přímo navržené pro indentaci? Proč místo toho používat tu klávesu jako fake-tab, který vloží do kódu několik znaků najednou? Proč pro odsazení bloku používat čtyři znaky (kde ty znaky nemají v původním významu nic společného s odsazením) namísto jednoho, který v editoru vizuálně mnohem lépe zobrazí odsazení bloku? Proč...

Chápu, že tohle je podobná svatá válka, jako problém, ze kterého konce se loupe banán :-) Ale pokud se vysloví ještě více lidí, že by chtěli odsazování podle PEP8, tak to v tomhle projektu překlopím (ač mírně nerad) na mezery. Zatím nechávám issue otevřenou.

**Comment by stinovlas** [comment]
Já považuju za hlavní problém tu vlastnost, že tabulátor je jeden znak, který má ale různou šířku, podle nastavení toho kterého editoru. Přijde mi lepší, když jsou všechny znaky v mém kódy vykresleny jako stejně široké (což by ovšem v případě tabulátoru znamenalo odsazení "o jednu mezeru", což by nebylo příliš přehledné). Navíc pak všichni vidí stejný, stejně poodsazovaný kód.

Jsem si celkem jist, že se najdou tací, co budou tutéž vlastnost považovat za velkou výhodu (každému může vyhovovat jiná úroveň odsazení, takže je správné, že ji můžu měnit).

**Comment by exander77** [comment]
Tak mně už je to jedno, ale do pull requestu přidávám na konec souboru:
`# vim: ts=4 sw=4 noexpandtab syntax=python
`
